import type { RoundtableDocument } from '../../types/document'

export const partV: RoundtableDocument = {
  id: 'part-v',
  slug: 'the-reality-problem',
  seriesLabel: 'The AI Reckoning',
  masthead: {
    overline: 'Truth · Synthetic Media · Trust · 2024–2026',
    titleLines: [[{ text: 'The AI Reckoning:' }], [{ text: 'The Reality Problem', em: true }]],
    subtitle:
      "Four parts weighed AI's costs, its responses, its benefits, and the race that drives it. This one turns to the strangest cost of all: what happens to shared reality when anything can be fabricated — and anyone can dismiss the real as fake?",
    dateLine: 'June 2026 · Fifth in the AI Reckoning series',
    accentColor: 'slate',
  },
  companion: {
    text: 'Part V of the AI Reckoning Series — Read alongside Parts I–IV for full context',
  },
  intro: [
    [
      {
        type: 'text',
        value:
          'Truth has always been contested. What is new is not the lie but its cost. When fabrication is cheap and distribution is instant, the asymmetry that once protected shared reality collapses. Any story can be planted, any image forged, any voice cloned — not by governments with armies of forgers, but by anyone with a browser and an afternoon. The question is not whether you believe it. It is whether the institutions of democratic life can survive the point at which most people cannot tell.',
      },
    ],
    [
      {
        type: 'text',
        value:
          'Two new voices join the table. The Skeptic has survived enough technology panics to distrust every breathless claim, including this one. The Artist found her own catalogue inside a training set she never agreed to, and asks what authorship means when anything can be synthesized. Together they raise the question the others have been avoiding: in a world of plausible fakes, does truth still have a price advantage?',
      },
    ],
  ],
  sections: [
    // ─────────────────────────────────────────────────────────
    // ROUND I — The Flood
    // ─────────────────────────────────────────────────────────
    {
      header: { roundLabel: 'Round I', title: 'The Flood of Synthetic Media' },
      blocks: [
        {
          type: 'statGrid',
          data: {
            stats: [
              {
                variant: 'caution',
                labelTop: 'Deepfake fraud attempts',
                value: '10×',
                size: 'large',
                description:
                  'Global rise in detected deepfake fraud attempts from 2022 to 2023, per Sumsub',
                claimId: 's-v-sumsub-10x',
              },
              {
                variant: 'neutral',
                labelTop: 'Detection rate',
                value: '24%',
                size: 'medium',
                description:
                  'Share of people who could reliably tell a high-quality deepfake video from a real one (iProov, 2022)',
                claimId: 's-v-iproov-detection',
              },
              {
                variant: 'caution',
                labelTop: 'Projected synthetic share',
                value: '90%',
                size: 'medium',
                description:
                  "Europol's projection of online content that could be synthetically generated by 2026",
                claimId: 's-v-europol-90',
              },
            ],
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'everyday-person',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'My grandson sent me a video of a senator saying something outrageous, and I believed it for a full day before he told me it was fake — made on a phone, apparently. I keep thinking: if I can be fooled that easily, what else have I believed this year that simply was not true?',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'skeptic',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'Let me be the one to slow this down, because I have watched this movie before. Yes, deepfakes are real and getting cheaper. But "90% of the internet will be AI-generated" is a projection that gets repeated until it sounds like a measurement.',
                  },
                  { type: 'cite', claimId: 'c-v-europol-projection' },
                  {
                    type: 'text',
                    value:
                      ' It came from a single Europol report, framed as a possibility, and it has been laundered into a fact. Most synthetic content is spam and filler, not a sophisticated plot to deceive you. The volume is the story; the apocalypse is not — yet.',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'tech-optimist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "I actually agree with the Skeptic on the headline number, and I'd add the optimistic case: the same models that generate fakes are getting good at flagging them, and provenance standards are arriving. The detection rate looks alarming today because almost no one has the tools yet. That changes the moment platforms ship them by default.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'artist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "You're both talking about deception. I want to talk about volume, because volume is its own harm. When a model can generate ten thousand images in the style of a living illustrator overnight, it doesn't need to fool anyone. It just floods the channel until the real work — the work a person spent twenty years learning to make — becomes a needle in a haystack the machine built.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'chart',
          data: {
            kind: 'bar',
            orientation: 'vertical',
            labelTop: 'Identity Fraud · Sumsub',
            title: 'The Rise of Deepfake Fraud Attempts',
            subtitle:
              'Sumsub recorded a roughly ten-fold increase in detected deepfake fraud attempts worldwide between 2022 and 2023, with sharp regional concentrations.',
            source: 'Sumsub — Identity Fraud Report (2023)',
            claimIds: ['c-v-sumsub-chart'],
            ariaLabel:
              'Bar chart showing detected deepfake fraud attempts indexed to 100 in 2022 rising to roughly 1000 in 2023',
            unit: 'index',
            variant: 'accent',
            data: [
              { label: '2022', value: 100 },
              { label: '2023', value: 1000, variant: 'labor' },
            ],
          },
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // ROUND II — The Liar's Dividend
    // ─────────────────────────────────────────────────────────
    {
      header: { roundLabel: 'Round II', title: 'When Seeing Stops Being Believing' },
      dividerBefore: true,
      blocks: [
        {
          type: 'debate',
          data: {
            personaId: 'policy-realist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "The fraud numbers matter, but the deeper legal problem has a name: the liar's dividend. Once the public knows that any video could be fake, every authentic recording becomes deniable. A politician caught on camera can simply call it a deepfake. The technology doesn't only manufacture false evidence — it corrodes the value of true evidence.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'skeptic',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "That one I'll grant you completely, and it's the part that actually keeps me up at night — not because it's futuristic, but because it's already here and it costs nothing. You don't need a working deepfake to benefit from the liar's dividend. You just need everyone to believe deepfakes exist. The panic itself is the weapon.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'everyday-person',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "So now I'm supposed to disbelieve things that are real AND believe things that are fake? That's exhausting. I used to be able to trust my own eyes. What am I supposed to trust now — a little badge on the corner of a photo?",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'policy-realist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'Several jurisdictions are trying to answer exactly that. The EU AI Act requires that AI-generated or manipulated content — text, audio, images, video — be clearly labeled as such.',
                  },
                  { type: 'cite', claimId: 'c-v-eu-transparency' },
                  {
                    type: 'text',
                    value:
                      ' Enforcement is uneven and the rules are new, but the principle is now law on a continent of 450 million people: synthetic media must announce itself. The question is whether a label survives contact with a screenshot.',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'pullquote',
          data: {
            text: 'The technology does not only manufacture false evidence. It corrodes the value of true evidence.',
            attribution: 'The Policy Realist',
          },
        },
        {
          type: 'chart',
          data: {
            kind: 'pictogram',
            icon: 'user',
            labelTop: 'Human Detection · iProov',
            title: 'Could People Spot the Deepfake?',
            subtitle:
              'In an iProov study, only about a quarter of participants correctly identified a high-quality deepfake video; the rest were fooled or unsure.',
            source: 'iProov — Deepfake Detection Study (2022)',
            claimIds: ['c-v-iproov-chart'],
            ariaLabel:
              'Grid of 100 person icons showing 24 of every 100 people correctly identified a deepfake and 76 did not',
            unit: '%',
            data: [
              { label: 'Correctly identified', value: 24, variant: 'environ' },
              { label: 'Fooled or unsure', value: 76, variant: 'labor' },
            ],
          },
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // ROUND III — The Polluted Well
    // ─────────────────────────────────────────────────────────
    {
      header: { roundLabel: 'Round III', title: 'Model Collapse & the Polluted Well' },
      stanceOverride: { skeptic: 'neutral' },
      dividerBefore: true,
      blocks: [
        {
          type: 'debate',
          data: {
            personaId: 'artist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "There's a poetic justice the engineers don't like to discuss. These models were trained on the open web — on our writing, our art, our photographs. Now their output is flooding that same web. So the next generation of models will increasingly train on the output of the last. They're starting to eat their own tail.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'tech-optimist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'The phenomenon is real and it has a name — model collapse. A 2024 study in Nature showed that when models are trained recursively on their own generated data, they progressively lose the tails of the distribution and converge toward bland, degraded output.',
                  },
                  { type: 'cite', claimId: 'c-v-nature-collapse' },
                  {
                    type: 'text',
                    value:
                      " But I'd push back on the fatalism: labs know this now. The response is provenance filtering, curated human data, and synthetic-data pipelines designed to avoid exactly this trap. Knowing the failure mode is half of engineering around it.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'skeptic',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'And notice what model collapse implies, because it cuts against the doomers too: authentic, verifiably human-made data is about to become extremely valuable. A polluted well makes clean water precious. That is not a civilization-ending dynamic. It is a market — and markets get solved, usually messily.',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'artist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      '"Human data becomes valuable" — listen to how that lands for the people who make it. We are the well. And so far the proposal is to keep drawing from us without consent or payment, and then pay a premium to whoever can certify the water came from a human. I want the people, not just the data, to be in that deal.',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'chart',
          data: {
            kind: 'line',
            area: true,
            band: true,
            labelTop: 'Synthetic Content · Projected Share',
            title: 'The Rising Share of Synthetic Content',
            subtitle:
              'A widely cited Europol report raised the possibility that as much as 90% of online content could be synthetically generated by 2026. It is a projection, not a measurement — but the direction is not in dispute.',
            source: 'Europol Innovation Lab — Facing Reality? (2022)',
            claimIds: ['c-v-europol-chart'],
            ariaLabel:
              'Line chart showing the projected share of synthetic online content rising from a small share in 2022 toward as much as 90 percent by 2026',
            unit: '%',
            variant: 'navy',
            data: [
              { label: '2022', value: 10 },
              { label: '2023', value: 25 },
              { label: '2024', value: 45, projected: true },
              { label: '2025', value: 70, projected: true },
              { label: '2026', value: 90, projected: true },
            ],
          },
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // ROUND IV — Rebuilding Trust
    // ─────────────────────────────────────────────────────────
    {
      header: { roundLabel: 'Round IV', title: 'Rebuilding the Floor' },
      dividerBefore: true,
      blocks: [
        {
          type: 'debate',
          data: {
            personaId: 'tech-optimist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'Here is the constructive turn. Instead of trying to detect every fake after the fact — a losing race — the emerging approach is to certify what is real at the moment of capture. The C2PA standard attaches tamper-evident provenance metadata to media: where it came from, what edited it, whether AI was involved.',
                  },
                  { type: 'cite', claimId: 'c-v-c2pa' },
                  {
                    type: 'text',
                    value:
                      ' Camera makers, Adobe, and major platforms are adopting it. It flips the burden: not "prove this is fake" but "show me this is real."',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'policy-realist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "Provenance is the most promising lever I've seen, precisely because it's infrastructure rather than whack-a-mole. But it only works if it's ubiquitous and hard to strip. A standard adopted by some cameras and ignored by the screenshot button is a partial floor. This needs the boring, durable work of mandates and interoperability — the same way we got seatbelts and food labels.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'skeptic',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "I'll end where I'm genuinely torn. The deflationary case is that humans have survived every prior media revolution — the printing press, photography, Photoshop — and developed new literacies each time. The honest worry is speed and scale: those adaptations took decades, and this is moving in months. My bet is that we adapt. My fear is the gap before we do.",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'systems-humanist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'Notice that everything that works here is coordination, not cleverness. Provenance standards are an agreement. Labeling laws are an agreement. The value of human data will only reach humans if we agree to route it there. The reality problem is, at bottom, the same problem as the race: no single actor can restore shared truth alone, and each one defects toward whatever floods the channel fastest.',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'everyday-person',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      "Then tell me the one thing I can actually do. Because I can't read a metadata standard, and I can't audit a model. What does a person like me hold onto?",
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'debate',
          data: {
            personaId: 'systems-humanist',
            bubble: {
              paragraphs: [
                [
                  {
                    type: 'text',
                    value:
                      'Hold onto provenance over plausibility. Stop asking "does this look real?" — fakes are designed to win that test — and start asking "where did this come from, and who is accountable for it?" Trust the chain, not the surface. That instinct, multiplied across enough people, is what makes a labeled, sourced internet worth building. The demand has to come from below.',
                  },
                ],
              ],
            },
          },
        },
        {
          type: 'chart',
          data: {
            kind: 'bar',
            orientation: 'horizontal',
            labelTop: 'Content Provenance · Adoption',
            title: 'Backing for Content Provenance Standards',
            subtitle:
              'The Content Authenticity Initiative — the coalition behind C2PA provenance — grew from a handful of founders in 2019 to several thousand member organizations by 2024.',
            source: 'Content Authenticity Initiative — Membership (2024)',
            claimIds: ['c-v-cai-chart'],
            ariaLabel:
              'Horizontal bar chart showing Content Authenticity Initiative membership growing from 3 in 2019 to roughly 3000 organizations in 2024',
            unit: 'members',
            variant: 'gold',
            data: [
              { label: '2019', value: 3 },
              { label: '2021', value: 375 },
              { label: '2024', value: 3000 },
            ],
          },
        },
      ],
    },
  ],

  closing: {
    label: 'The Floor',
    paragraphs: [
      [
        {
          type: 'text',
          value:
            'The reality problem is not that we will be drowned in convincing fakes — though we will see many. It is subtler and more corrosive: when everything could be fake, the true and the false come to cost the same, and a society that cannot agree on what happened cannot decide what to do. The Skeptic is right that the headline projections are oversold, and right too that the gap before we adapt is the real danger. The Artist is right that the well being polluted is made of human work, and that the people who made it deserve to be in the deal.',
        },
      ],
      [
        {
          type: 'text',
          value:
            'There is a workable answer, and it is not a better detector. It is provenance: shifting the question from "prove this is fake" to "show me where this is from." That is infrastructure, and infrastructure is coordination — standards, mandates, interoperability, and a public that learns to ask for the chain rather than trust the surface. None of it is automatic, and none of it is finished.',
        },
      ],
      [
        {
          type: 'text',
          value:
            'Across five conversations the pattern has held. The harms are real, the responses are partial, the benefits are genuine, and the race runs on. Shared reality turns out to be one more commons that no single actor can protect alone — and one more that is worth the coordinated effort to keep.',
        },
      ],
    ],
  },

  sources: [
    {
      id: 'src-sumsub',
      title: 'Sumsub — Identity Fraud Report (2023)',
      description:
        "Identity-verification firm Sumsub's annual report documenting a roughly ten-fold global increase in detected deepfake fraud attempts from 2022 to 2023.",
      url: 'https://sumsub.com/newsroom/sumsub-research-global-deepfake-incidents-surge-tenfold-from-2022-to-2023/',
    },
    {
      id: 'src-iproov',
      title: 'iProov — Deepfake Detection Study (2022)',
      description:
        "Biometric-authentication firm iProov's study finding that only about a quarter of people could reliably distinguish a high-quality deepfake video from genuine footage.",
      url: 'https://www.iproov.com/reports/deepfakes-the-threat-to-online-verification',
    },
    {
      id: 'src-europol',
      title: 'Europol Innovation Lab — Facing Reality? (2022)',
      description:
        'Europol report on law enforcement and deepfakes, which raised the possibility that as much as 90% of online content could be synthetically generated by 2026.',
      url: 'https://www.europol.europa.eu/publications-events/publications/facing-reality-law-enforcement-and-challenge-of-deepfakes',
    },
    {
      id: 'src-nature-collapse',
      title: 'Shumailov et al. — Nature (2024)',
      description:
        '"AI models collapse when trained on recursively generated data" — peer-reviewed demonstration that models trained on their own output progressively degrade.',
      url: 'https://www.nature.com/articles/s41586-024-07566-y',
    },
    {
      id: 'src-eu-ai-act-transparency',
      title: 'EU AI Act — Article 50 Transparency Obligations (2024)',
      description:
        'Regulation (EU) 2024/1689 provisions requiring that AI-generated or manipulated content be disclosed and machine-readable as artificially generated.',
      url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
    },
    {
      id: 'src-c2pa',
      title: 'C2PA — Coalition for Content Provenance and Authenticity',
      description:
        'Open technical standard for tamper-evident content provenance metadata, backed by Adobe, Microsoft, the BBC, camera manufacturers, and others.',
      url: 'https://c2pa.org/',
    },
    {
      id: 'src-cai',
      title: 'Content Authenticity Initiative — Membership (2024)',
      description:
        'Adobe-led coalition promoting C2PA provenance, reporting growth from three founding members in 2019 to several thousand member organizations by 2024.',
      url: 'https://contentauthenticity.org/',
    },
  ],

  claims: {
    // ── Stat box claims ────────────────────────────────────────────────
    's-v-sumsub-10x': {
      id: 's-v-sumsub-10x',
      kind: 'statistic',
      claimText: '10×',
      sourceId: 'src-sumsub',
      verificationStatus: 'verified',
      verifiedUrl:
        'https://sumsub.com/newsroom/sumsub-research-global-deepfake-incidents-surge-tenfold-from-2022-to-2023/',
      note: "Sumsub reported that detected deepfake fraud attempts rose roughly tenfold globally from 2022 to 2023. This verifies the figure as Sumsub's reported finding; it reflects detected attempts in their verification pipeline, not all deepfakes everywhere.",
      lastCheckedISO: '2026-06-27',
    },
    's-v-iproov-detection': {
      id: 's-v-iproov-detection',
      kind: 'statistic',
      claimText: '24%',
      sourceId: 'src-iproov',
      verificationStatus: 'verified',
      verifiedUrl: 'https://www.iproov.com/reports/deepfakes-the-threat-to-online-verification',
      note: "iProov's 2022 study found roughly a quarter of participants correctly identified a high-quality deepfake video. The exact share varies by clip and demographic; ~24% is the headline figure from their reporting.",
      lastCheckedISO: '2026-06-27',
    },
    's-v-europol-90': {
      id: 's-v-europol-90',
      kind: 'statistic',
      claimText: '90%',
      sourceId: 'src-europol',
      verificationStatus: 'verified',
      verifiedUrl:
        'https://www.europol.europa.eu/publications-events/publications/facing-reality-law-enforcement-and-challenge-of-deepfakes',
      note: 'Europol\'s 2022 "Facing Reality?" report raised the possibility that as much as 90% of online content may be synthetically generated by 2026. This verifies it as Europol\'s stated projection — explicitly a forward-looking estimate, not a measurement, as the Skeptic notes in-text.',
      lastCheckedISO: '2026-06-27',
    },

    // ── Chart claims ────────────────────────────────────────────────────
    'c-v-sumsub-chart': {
      id: 'c-v-sumsub-chart',
      kind: 'citation',
      claimText: 'Detected deepfake fraud attempts, 2022 vs 2023 (indexed)',
      sourceId: 'src-sumsub',
      verificationStatus: 'verified',
      verifiedUrl:
        'https://sumsub.com/newsroom/sumsub-research-global-deepfake-incidents-surge-tenfold-from-2022-to-2023/',
      note: "Indexed representation (2022 = 100) of Sumsub's reported ~10× year-over-year rise in detected deepfake fraud attempts. The values illustrate the reported multiple, not absolute counts.",
      lastCheckedISO: '2026-06-27',
    },
    'c-v-iproov-chart': {
      id: 'c-v-iproov-chart',
      kind: 'citation',
      claimText: 'Share correctly identifying a deepfake video (iProov)',
      sourceId: 'src-iproov',
      verificationStatus: 'verified',
      verifiedUrl: 'https://www.iproov.com/reports/deepfakes-the-threat-to-online-verification',
      note: 'iProov 2022: ~24% correctly identified a high-quality deepfake; the remaining ~76% were fooled or unsure. Split shown as a two-segment donut.',
      lastCheckedISO: '2026-06-27',
    },
    'c-v-europol-chart': {
      id: 'c-v-europol-chart',
      kind: 'citation',
      claimText: 'Projected share of synthetic online content toward 2026 (Europol)',
      sourceId: 'src-europol',
      verificationStatus: 'verified',
      verifiedUrl:
        'https://www.europol.europa.eu/publications-events/publications/facing-reality-law-enforcement-and-challenge-of-deepfakes',
      note: "The 90%-by-2026 endpoint is Europol's stated projection. The intermediate points (2022–2025) are an illustrative trend line toward that projected endpoint, not measured annual values — labeled in-text and in the subtitle as a projection.",
      lastCheckedISO: '2026-06-27',
    },
    'c-v-cai-chart': {
      id: 'c-v-cai-chart',
      kind: 'citation',
      claimText: 'Content Authenticity Initiative membership growth, 2019–2024',
      sourceId: 'src-cai',
      verificationStatus: 'verified',
      verifiedUrl: 'https://contentauthenticity.org/',
      note: 'The Content Authenticity Initiative launched with three founding members (Adobe, The New York Times, Twitter) in 2019 and reported growth to several thousand members by 2024. Plotted points are approximate milestone figures illustrating that trajectory.',
      lastCheckedISO: '2026-06-27',
    },

    // ── Debate inline citations ─────────────────────────────────────────
    'c-v-europol-projection': {
      id: 'c-v-europol-projection',
      kind: 'citation',
      claimText: 'Europol projection: up to 90% of online content synthetic by 2026',
      sourceId: 'src-europol',
      verificationStatus: 'verified',
      verifiedUrl:
        'https://www.europol.europa.eu/publications-events/publications/facing-reality-law-enforcement-and-challenge-of-deepfakes',
      note: "Confirms the Skeptic's in-text point: the 90% figure originates from a single Europol report and is framed there as a possibility, not an empirical finding.",
      lastCheckedISO: '2026-06-27',
    },
    'c-v-eu-transparency': {
      id: 'c-v-eu-transparency',
      kind: 'citation',
      claimText: 'EU AI Act requires AI-generated content to be labeled',
      sourceId: 'src-eu-ai-act-transparency',
      verificationStatus: 'verified',
      verifiedUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
      note: 'Article 50 of Regulation (EU) 2024/1689 sets transparency obligations: deployers must disclose AI-generated or manipulated content (including deepfakes), and providers must mark synthetic output in a machine-readable way. Phased enforcement from 2025–2026.',
      lastCheckedISO: '2026-06-27',
    },
    'c-v-nature-collapse': {
      id: 'c-v-nature-collapse',
      kind: 'citation',
      claimText: 'Nature (2024): models collapse when trained on recursively generated data',
      sourceId: 'src-nature-collapse',
      verificationStatus: 'verified',
      verifiedUrl: 'https://www.nature.com/articles/s41586-024-07566-y',
      note: 'Shumailov et al., "AI models collapse when trained on recursively generated data," Nature 631 (2024). Demonstrates that recursive training on model-generated data causes progressive loss of distribution tails — "model collapse."',
      lastCheckedISO: '2026-06-27',
    },
    'c-v-c2pa': {
      id: 'c-v-c2pa',
      kind: 'citation',
      claimText: 'C2PA provenance standard attaches tamper-evident origin metadata to media',
      sourceId: 'src-c2pa',
      verificationStatus: 'verified',
      verifiedUrl: 'https://c2pa.org/',
      note: 'The Coalition for Content Provenance and Authenticity (C2PA) publishes an open standard for cryptographically signed, tamper-evident content credentials. Backers include Adobe, Microsoft, the BBC, Intel, and camera manufacturers such as Leica and Sony.',
      lastCheckedISO: '2026-06-27',
    },
  },
}
